export const typography = {
  screenTitle: {
    fontFamily: 'Montserrat_700Bold',
    fontSize: 32,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 38,
  },
  sectionTitle: {
    fontFamily: 'Montserrat_700Bold',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 27,
  },
  body: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 22,
  },
  label: {
    fontFamily: 'Montserrat_700Bold',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 22,
  },
  caption: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 17,
  },
  button: {
    fontFamily: 'Montserrat_700Bold',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 20,
  },
  tabLabel: {
    fontFamily: 'Montserrat_700Bold',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 15,
  },
} as const;
